
  version: "3.9"

  services:
    postgres:
      image: postgres:latest
      hostname: postgres
      environment:
        # libqp env var for healthcheck
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: mysecretpassword
      ports:
        - 5432:5432
      healthcheck:
        test: pg_isready
        interval: 1s
        retries: 5
        start_period: 1s
        timeout: 10s