version: "3.9"

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      # libqp env var for healthcheck
      - PGUSER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready
      interval: 1s
      retries: 5
      start_period: 1s
      timeout: 10s
